### ISSUE TITLE
Mac Support

### ISSUE THREAD

**Issue by lterfloth** [cyberneuron/RT-CNN-Vis#1]
Hey there, 

the project looks very promising. I dove into the whole topic a little and it seems that Mac OS (more precisely http://www.xhyve.xyz/ ) doesn't support PCI passthrough (at least it didn't in May 2016 - so things might've changed). Are there any ways to get the RT-CNN-Vis running using Docker (or manually) on Mac OS Mojave? 
Thank you for your time and hard work, have a Happy New Year!

**Comment by partus** [comment]
Hey,
We didn't try to run it on Mac OS. It would be a nice extension to have.
The main requirements are to have tensorflow-gpu and OpenCV >3.4.3 running with python >=3.6.
So  I suppose the main problem is to make tensorflow-gpu  running.
If it's possible to make it running with docker that would be great. if the image should differ, then a new docker file should be created. 
If it's not possible but tensorflow-gpu can run on Mac Os then installation should be quite similar to steps in Dockerfile (or the requirements should be clear from the Dockerfile).
The last option would be to run without gpu   support but then you will get real-time feeling only with very lightweight networks. This would be nice in any case for a computer without gpu.
Please message back what you end up with.

Thank you for the interest, contribution is welcome. Happy New Year!

**Comment by partus** [comment]
A new dockerfile called Dockerfile.cpu is introduced, so you should be able to run the project on MAC OS at least in CPU mode. Check the update in the README. Please report back if you succeed with running on GPU on MAC OS.

**Comment by lterfloth** [comment]
Hey partus, looks promising! I'll try it as soon as I got the time for it (got exams right now). Cheers for the effort!
