### ISSUE TITLE
Does this project be run in CPU mode without GPU?

### ISSUE THREAD

**Issue by TomHJ** [cyberneuron/RT-CNN-Vis#2]
This is a wonderful project. I would like to have a try in my deep learning study journey. But my notebook has not GPU. So i am not sure if this project can be run only in CPU mode. Thanks

**Comment by partus** [comment]
Thanks. A new dockerfile called  Dockerfile.cpu is introduced, you can run the project on CPU only using that dockerfile. Check the update in the README.
